---
title: "Series temporales Paracas Bay"
author: "Edgart Flores"
date: "11/17/2020"
output: html_document
---
```{r cars}
library(dataRetrieval)
require(ggplot2)
require(visreg)
require(MASS)
require(reshape2)
library(scales)
library(dplyr)
library(gridExtra)
library(ggpubr)
library(vegan)
library(scales)
library(dplyr)
library(lubridate)
library(ggpmisc)
library(scales)

library(dplyr)
library(plotly)
```

```{r pressure, echo=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(dplyr)
library(tidyverse)
library(latex2exp)
library(readxl)
library(here) 
library(broom)
library(devtools)
library(ggpubr)
library(tidyverse) 
library(scales) 
library(stringr) 
library(Hmisc) 
library(forcats) 
library(ggthemes) 
```


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r cars}
read.csv("~/Documents/PARACAS_BABY/data_paper/DatosPaperEdgart.csv")
```

```{r pressure, echo=FALSE}
#Leemos datos
table = read.csv(file="~/Documents/PARACAS_BABY/data_paper/DatosPaperEdgart.csv") #Tabla cruda
table$time = as.Date(table$time, format = "%d/%m/%Y")

#Vector de estratificación
dt = table$ts - table$tf

language <- "English" 
Sys.setlocale("LC_TIME", language) 

ticks = seq(from=table$time[1], to=table$time[length(table$time)], by="months")

attach(table)

#x11()
par(mfrow=c(3,1))
par(mar=c(0,4,1,4))
plot(time, wind_speed, type='l', ylim=c(0,12), xlab='', ylab='', xaxt="n", yaxt='n', xaxs="i", yaxs="i", lwd=1)
axis(2, col="black", col.axis="black", lwd=1, las=1, cex.axis=1)
mtext(2, text=expression(paste('Wind intensity (m.',s^-1, ')')), line=2.1, col="black", las=3, cex=0.9, font=1)
text(time[5], 10, 'A', cex=2)
polygon(as.Date(c("2015-03-09","2015-03-09","2015-03-23","2015-03-23"),
                format = "%Y-%m-%d"), c(0,12,12,0), col=rgb(0,0,0,alpha=0.2), border=NA)
polygon(as.Date(c("2015-04-18","2015-04-18","2015-04-19","2015-04-19"),
                format = "%Y-%m-%d"), c(0,8,8,0), col=rgb(0,0,0,alpha=0.2), border=NA)

par(mar=c(0,4,0,4))
plot(time, tf, type='l', lwd=1, xlab='', ylab='', xaxt="n", yaxt="n", yaxs="i", xaxs="i", ylim=c(14,24))
lines(time,clim_tf, lwd=1, lty=2)
axis(4, col="black", col.axis="black",lwd=1, las=1, cex.axis=1)
mtext(4,text="Bottom water temperature (°C)", line=2.2, col="black", las=3, cex=0.9, font=1)
text(time[5],22,'B', cex=2)
polygon(as.Date(c("2015-03-09","2015-03-09","2015-03-23","2015-03-23"),
                format = "%Y-%m-%d"), c(14,24,24,14), col=rgb(0,0,0,alpha=0.2), border=NA)
polygon(as.Date(c("2015-04-18","2015-04-18","2015-04-19","2015-04-19"),
                format = "%Y-%m-%d"), c(0,8,8,0), col=rgb(0,0,0,alpha=0.2), border=NA)

par(mar=c(2,4,0,4))
plot(time, dt, ylim=c(0,8), type='l', xlab='', ylab='', yaxs="i", xaxs='i', xaxt="n", yaxt="n", lwd=1)
axis(2, lwd=1, las=1, cex.axis=1)
mtext(2, text=expression(paste(Delta,'T (°C)')), line=2.1, las=3, cex=0.9)
text(time[5],6,'C', cex=2)
axis.Date(side=1, time, at=ticks, format = "%b-%Y", las=1, font=1, cex.axis=1.1)
polygon(as.Date(c("2015-03-09","2015-03-09","2015-03-23","2015-03-23"),
                format = "%Y-%m-%d"), c(0,8,8,0), col=rgb(0,0,0,alpha=0.2), border=NA)
polygon(as.Date(c("2015-04-18","2015-04-18","2015-04-19","2015-04-19"),
                format = "%Y-%m-%d"), c(0,8,8,0), col=rgb(0,0,0,alpha=0.2), border=NA)
```

```{r pressure, echo=FALSE}
#x11()
par(mfrow=c(3,1))
par(mar=c(0,4,1,4))
plot(time, wind_speed, type='l', ylim=c(0,12), xlab='', ylab='', xaxt="n", yaxt='n', xaxs="i", yaxs="i", lwd=1)
axis(2, col="black", col.axis="black", lwd=1, las=1, cex.axis=1)
mtext(2, text=expression(paste('Wind intensity (m.',s^-1, ')')), line=2.1, col="black", las=3, cex=0.9, font=1)
text(time[5], 10, 'A', cex=2)
polygon(as.Date(c("2015-03-16","2015-03-16","2015-03-23","2015-03-23"),
                format = "%Y-%m-%d"), c(0,12,12,0), col=rgb(0,0,0,alpha=0.2), border=NA)
polygon(as.Date(c("2015-04-18","2015-04-18","2015-04-19","2015-04-19"),
                format = "%Y-%m-%d"), c(0,12,12,0), col=rgb(0,0,0,alpha=0.2), border=NA)



ggplot(data = table) +
  geom_smooth(mapping = aes(x = time, y = wind_speed)) +
  geom_line(data = table, aes(x = time, y = wind_speed))

library(splines)
ggplot(aes(x = time, y = wind_speed, color = wind_speed ), data = table) +
  geom_point(color = 'black') +
  stat_smooth(method = 'lm', formula = y ~ ns(x, 10), size=0.5) #+ 
# geom_smooth(span = 0.8, fill = "red", colour = "red4", 
#              lty = 2, size = 0.1)

# Gráfico 2
p1 <- ggplot(table, aes(time, wind_speed)) + 
  geom_path(colour = "grey50", lty = 5) +
  geom_point(aes(colour = time), size = 2) +
  xlab('time') + 
  ylab(expression(paste('Wind intensity (m.',s^-1, ')'))) +
geom_rect(data = table, 
          aes(xmin = as.Date("2015-04-18", "%Y-%m-%d"), 
              xmax = as.Date("2015-04-19",  "%Y-%m-%d"),
              ymin = -Inf, 
              ymax = Inf),
          fill = "gray", 
          alpha = 0.01) +
geom_rect(data = table, 
          aes(xmin = as.Date("2015-03-16", "%Y-%m-%d"), 
              xmax = as.Date("2015-03-23",  "%Y-%m-%d"),
              ymin = -Inf, 
              ymax = Inf),
          alpha = 0.01,
          fill = "gray" 
          )
  
p1

```

```{r pressure, echo=FALSE}
# Gráfico 2

p2 <- ggplot(table, aes(time, tf)) + 
  geom_path(colour = "grey50", lty = 5) +
  geom_point(aes(colour = time), size = 2) + 
  geom_line(aes(y = clim_tf), color = "black", linetype = "dashed") +
  xlab('time') + 
  ylab('Bottom water temperature (°C)') +
geom_rect(data = table, 
          aes(xmin = as.Date("2015-04-18", "%Y-%m-%d"), 
              xmax = as.Date("2015-04-19",  "%Y-%m-%d"),
              ymin = -Inf, 
              ymax = Inf),
          fill = "gray", 
          alpha = 0.01) +
geom_rect(data = table, 
          aes(xmin = as.Date("2015-03-16", "%Y-%m-%d"), 
              xmax = as.Date("2015-03-23",  "%Y-%m-%d"),
              ymin = -Inf, 
              ymax = Inf),
          alpha = 0.01,
          fill = "gray" 
          )
p2 

```

```{r pressure, echo=FALSE}
# Gráfico 2
p3 <- ggplot(table, aes(time, dt)) + 
  geom_path(colour = "grey50", lty = 5) +
  geom_point(aes(colour = time), size = 2) +
  xlab('time') + 
  ylab(expression(paste(Delta,'T (°C)'))) +
geom_rect(data = table, 
          aes(xmin = as.Date("2015-04-18", "%Y-%m-%d"), 
              xmax = as.Date("2015-04-19",  "%Y-%m-%d"),
              ymin = -Inf, 
              ymax = Inf),
          fill = "gray", 
          alpha = 0.01) +
geom_rect(data = table, 
          aes(xmin = as.Date("2015-03-16", "%Y-%m-%d"), 
              xmax = as.Date("2015-03-23",  "%Y-%m-%d"),
              ymin = -Inf, 
              ymax = Inf),
          alpha = 0.01,
          fill = "gray" 
          )
  
p3 
```

```{r cars}
figure<- ggarrange (p1,p2,p3,
                    labels = c("A","B","C"),
                    ncol = 1, nrow = 6)
figure
```

```{r pressure, echo=FALSE}
#dtm <- read.delim("~/Documents/PARACAS_BABY/data_paper/out_1.csv", sep=",", header = T)
dtm <- read.delim("~/Documents/PARACAS_BABY/data_paper/out_2.csv", sep=",", header = T)
  
p4 <- ggplot(dtm, aes(time, oxy, group=stations, colour=stations)) + 
  geom_line(aes(y = oxy), color = "black", linetype = "dashed")  
p4 <- p4 + geom_point(size=2) + 
  scale_color_manual("dtm", 
       values = c("s1" = "#999999",  "s2" = "peru", "s3" = "steelblue")) +
  xlab('time') + 
  ylab("Oxygen (uM)") + 
  scale_x_discrete(breaks = c("4/1/15", "5/1/15","6/1/15", "7/1/15")) +
  geom_rect(data=dtm[1,], xmin=11,ymin=0,xmax=12,ymax=200, fill="cyan2",alpha=0.4)
p4
```

```{r pressure, echo=FALSE}
#dtm <- read.delim("~/Documents/PARACAS_BABY/data_paper/out_1.csv", sep=",", header = T)
dtm <- read.delim("~/Documents/PARACAS_BABY/data_paper/out_2.csv", sep=",", header = T)
  
p5 <- ggplot(dtm, aes(time, temp, group=stations, colour=stations)) + 
  geom_line(aes(y = temp), color = "black", linetype = "dashed")  
p5 <- p5 + geom_point(size=2) + 
  scale_color_manual("dtm", 
       values = c("s1" = "#999999",  "s2" = "peru", "s3" = "steelblue")) +
  xlab('time') + 
  ylab("Temperature (°C)") + 
  scale_x_discrete(breaks = c("4/1/15", "5/1/15","6/1/15", "7/1/15")) + 
  scale_x_discrete(breaks = c("4/1/15", "5/1/15","6/1/15", "7/1/15")) +
  geom_rect(data=dtm[1,], xmin=20,ymin=0,xmax=21,ymax=200, fill="gray",alpha=0.4)
p5
```



# ATERNATIVA

```{r pressure, echo=FALSE}
dtm <- read.delim("~/Documents/PARACAS_BABY/data_paper/data_oxy_temp2.csv", sep=",", header = T)
```

```{r pressure, echo=FALSE}
#Calcular medias por grupos de todas las columnas
average_daily = dtm%>%group_by(date1,Stations)%>%
  summarise_all(mean)
average_daily
```

```{r, message=FALSE}
average_daily <- average_daily  %>%
  mutate(SampleType2 =
           case_when(grepl("1", date1) ~ "Hipoxic conditions",
                     grepl("2", date1) ~ "Hipoxic conditions",
                     grepl("3", date1) ~ "Hipoxic conditions",
                     grepl("4", date1) ~ "Hipoxic conditions",
                     grepl("5", date1) ~ "Hipoxic conditions",
                     grepl("6", date1) ~ "Hipoxic conditions",
                     grepl("7", date1) ~ "Hipoxic conditions",
                     grepl("8", date1) ~ "Hipoxic conditions",
                     grepl("9", date1) ~ "Hipoxic conditions",
                     grepl("10", date1) ~ "Hipoxic conditions",
                     grepl("11", date1) ~ "Hipoxic conditions",
                     grepl("12", date1) ~ "Hipoxic conditions",
                     grepl("13", date1) ~ "Hipoxic conditions",
                     grepl("14", date1) ~ "Hipoxic conditions",
                     grepl("15", date1) ~ "Hipoxic conditions",
                     grepl("16", date1) ~ "Hipoxic conditions",
                     grepl("17", date1) ~ "Hipoxic conditions",
                     grepl("18", date1) ~ "Hipoxic conditions",
                     grepl("19", date1) ~ "Hipoxic conditions",
                     grepl("20", date1) ~ "Hipoxic conditions",
                     grepl("21", date1) ~ "Hipoxic conditions",
                     grepl("22", date1) ~ "Hipoxic conditions",
                     grepl("23", date1) ~ "Hipoxic conditions",
                     grepl("24", date1) ~ "Hipoxic conditions",
                     grepl("25", date1) ~ "Hipoxic conditions",
                     grepl("26", date1) ~ "Hipoxic conditions",
                     grepl("27", date1) ~ "Hipoxic conditions",
                     grepl("28", date1) ~ "Oxic conditions",
                     grepl("29", date1) ~ "Oxic conditions",
                     grepl("30", date1) ~ "Oxic conditions",
                     grepl("31", date1) ~ "Oxic conditions",
                     grepl("32", date1) ~ "Oxic conditions",
                     grepl("33", date1) ~ "Oxic conditions",
                     grepl("34", date1) ~ "Oxic conditions",
                     grepl("35", date1) ~ "Oxic conditions",
                     grepl("36", date1) ~ "Oxic conditions",
                     grepl("37", date1) ~ "Oxic conditions",
                     grepl("38", date1) ~ "Oxic conditions",
                     grepl("39", date1) ~ "Oxic conditions",
                     grepl("40", date1) ~ "Oxic conditions",
                     grepl("41", date1) ~ "Oxic conditions",
                     grepl("42", date1) ~ "Oxic conditions",
                     grepl("43", date1) ~ "Oxic conditions",
                     grepl("44", date1) ~ "Oxic conditions",
                     grepl("45", date1) ~ "Oxic conditions",
                     grepl("46", date1) ~ "Oxic conditions",
                     grepl("47", date1) ~ "Oxic conditions",
                     grepl("48", date1) ~ "Oxic conditions",
                     grepl("49", date1) ~ "Oxic conditions",
                     grepl("50", date1) ~ "Oxic conditions",
                     grepl("51", date1) ~ "Oxic conditions",
                     grepl("52", date1) ~ "Oxic conditions",
                     grepl("53", date1) ~ "Oxic conditions",
                     grepl("54", date1) ~ "Oxic conditions",
                     grepl("55", date1) ~ "Oxic conditions",
                     grepl("56", date1) ~ "Oxic conditions",
                     grepl("57", date1) ~ "Oxic conditions",
                     grepl("58", date1) ~ "Oxic Conditions"))
```

# lo que hice fue descargar la tabla de los promedios y anexarle manualmente las dos compenentes (SampleType) aunque innecesario para este grafico 

```{r cars}
#average_daily
#write.csv(average_daily, file="average_daily.csv")
average_daily <- read.delim("~/Documents/PARACAS_BABY/data_paper/average_daily.csv", sep=",")
```


```{r cars}
O <- ggplot(average_daily, aes(date1, oxy)) + 
  geom_point(data = average_daily, aes(x = date1, y = oxy, color = Stations)) +
  scale_color_manual(values=c("#999999", "peru", "steelblue")) +
 facet_wrap(~ factor(SampleType2,levels=c("Suboxic conditions","Dysoxic conditions")), ncol = 2, scales = "free_x") +
  geom_smooth(orientation = "x") + scale_x_continuous(
  breaks = c(1, 8.5, 16, 23.6, 31 ,38, 45, 52, 58),
  label = c("12 April-15", "19 April-15","26 April-15", 
                             "03 May-15", "10 May-15","17 May-15", "24 May-15","31 May-15", "07 Jun-15")) + 
  theme(axis.text.x = element_text(angle = 10)) +
  xlab(" ") +  ylab("Oxygen (uM)") + 
  #geom_hline(yintercept=10, size=0.2, color = "blue") + 
  geom_hline(yintercept=10, size=0.4, color = "brown1") 

O
```

```{r cars}
T <- ggplot(average_daily, aes(date1, temp)) + 
  geom_point(data = average_daily, aes(x = date1, y = temp, color = Stations)) +
  scale_color_manual(values=c("#999999", "peru", "steelblue")) +
  facet_wrap(~ factor(SampleType2,levels=c("Suboxic conditions","Dysoxic conditions")), ncol = 2, scales = "free_x") +
  geom_smooth(orientation = "x") + scale_x_continuous(
  breaks = c(1, 8.5, 16, 23.6, 31 ,38, 45, 52, 58),
  label = c("12 April-15", "19 April-15","26 April-15", 
                             "03 May-15", "10 May-15","17 May-15", "24 May-15","31 May-15", "07 Jun-15")) + 
  theme(axis.text.x = element_text(angle = 10)) +
  xlab("date") +  ylab("Temperature (°C)")  
  #geom_hline(yintercept=10, size=0.2, color = "blue") + 
  #geom_hline(yintercept=10, size=0.2, color = "red") 
T
```



```{r cars}
figure<- ggarrange (T,O,p7,
                    labels = c("A","B","C"),
                    ncol = 1, nrow = 3)
figure
```

```{r pressure, echo=FALSE}
#https://ocean.ices.dk/tools/unitconversion.aspx
dtm <- read.delim("~/Documents/PARACAS_BABY/data_paper/data_paracas_bay.csv", sep=",", header = T)

p3 <- ggplot(dtm, aes(time, oxy_s1)) + 
  geom_path(colour = "grey50", lty = 5) +
  geom_rect(data=dtm, mapping=aes(xmin=20, xmax=30, ymin = 0, ymax=320), color="gray", alpha = .125) + geom_point(aes(colour = oxy_s1), size = 2) 
  
p3 
```

```{r pressure, echo=FALSE}
dtm <- read.delim("~/Documents/PARACAS_BABY/data_paper/data_paracas_bay.csv", sep=",", header = T)

p4 <- ggplot(dtm, aes(time, oxy_s2)) + 
  geom_path(colour = "grey50", lty = 5) +
  geom_point(aes(colour = oxy_s1), size = 2)
  
p4 


mean_data1 <- dtm %>% 
  group_by(time, oxy_s1) %>% 
  summarise(Mean = mean(oxy_s1, na.rm = TRUE))
mean_data1
```

```{r pressure, echo=FALSE}
library(reshape2)
data <- read.delim("~/Documents/PARACAS_BABY/data_paper/flux_mmol_1.csv", sep=",")
```
# add a new column : SampleType
```{r, message=FALSE}
data <- data  %>%
  mutate(SampleType =
           case_when(grepl("1", dose) ~ "Anoxic Conditions",
                     grepl("2", dose) ~ "Anoxic Conditions",
                     grepl("3", dose) ~ "Anoxic Conditions",
                     grepl("4", dose) ~ "Anoxic Conditions",
                     grepl("5", dose) ~ "Oxic Conditions",
                     grepl("6", dose) ~ "Oxic Conditions",
                     grepl("7", dose) ~ "Oxic Conditions",
                     grepl("8", dose) ~ "Oxic Conditions"
                     ))
```


```{r pressure, echo=FALSE}
## use the interaction between the variables to define the grouping
p7 <- ggplot(data, aes(dose, len , fill=interaction(supp))) + 
  geom_bar(aes(), stat='identity', position='dodge') +
facet_wrap(~ SampleType, ncol = 2, scales = "free_x") + 
  scale_fill_manual(values = c("#999999", "peru", "steelblue")) +  
#  coord_cartesian(xlim = c(1, 8), ylim = c(-0.2,4.3))   +
#  scale_x_continuous(breaks = round(seq(min(data$dose), max(data$dose), by = 1),1)) +
  xlab("date") +  ylab(expression("Hydrogen sulfide fluxes (m. mol." ~ m^2 *"" ~ d^-1 *")")) + 
  geom_hline(yintercept=0, size=0.2) 

p7 + scale_x_continuous(
  breaks = c(1, 2, 3, 4, 5, 6, 7, 8),
  label = c("12 April-15", "19 April-15","26 April-15", 
                             "03 May-15", "17 May-15", "24 May-15","31 May-15", "07 Jun-15")) + 
  theme(axis.text.x = element_text(angle = 10)) + labs(fill = "Stations")
p7
```

```{r pressure, echo=FALSE}
#dtm <- read.delim("~/Documents/PARACAS_BABY/data_paper/out_1.csv", sep=",", header = T)
dtm <- read.delim("~/Documents/PARACAS_BABY/data_paper/out_2.csv", sep=",", header = T)
  
p4 <- ggplot(dtm, aes(time, oxy, group=stations, colour=stations)) + 
  geom_line(aes(y = oxy), color = "black", linetype = "dashed")  
p5 <- p4 + geom_point(size=2) + 
  scale_color_manual("dtm", 
       values = c("s1" = "#999999",  "s2" = "peru", "s3" = "steelblue")) +
  xlab('time') + 
  ylab("Oxygen (uM)") + 
  scale_x_discrete(breaks = c("4/1/15", "5/1/15","6/1/15", "7/1/15"))
p5
```

```{r pressure, echo=FALSE}
#dtm <- read.delim("~/Documents/PARACAS_BABY/data_paper/out_1.csv", sep=",", header = T)
dtm <- read.delim("~/Documents/PARACAS_BABY/data_paper/out_2.csv", sep=",", header = T)
  
p5 <- ggplot(dtm, aes(time, temp, group=stations, colour=stations)) + 
  geom_line(aes(y = temp), color = "black", linetype = "dashed")  
p6 <- p5 + geom_point(size=2) + 
  scale_color_manual("dtm", 
       values = c("s1" = "#999999",  "s2" = "peru", "s3" = "steelblue")) +
  xlab('time') + 
  ylab("Temperature") + 
  scale_x_discrete(breaks = c("4/1/15", "5/1/15","6/1/15", "7/1/15"))
p6
```

```{r cars}
figure<- ggarrange (p1,p2,p3,p5,p6,p7,
                    labels = c("A","B","C"),
                    ncol = 1, nrow = 7)
figure
```
